stages:
  - package and deploy

package and deploy:
  tags:
    - dind-runner
  when: manual
  stage: package and deploy
  image: maven:3.8.6-openjdk-11
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
  before_script:
    - apt-get update && apt-get -y upgrade && apt-get install -y curl unzip jq
    - |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
      unzip awscliv2.zip && \
      ./aws/install
  script:
    - mvn clean package
    - NEW_JARID=$(curl -X POST -H "Expect:" -F "jarfile=@./target/mysqlcdc-elasticsearch-1.0-SNAPSHOT.jar" $FLINK_CLUSTER/jars/upload  | jq -r '.filename' | awk -F/ '{print $NF}')
    - echo $NEW_JARID
    - UPDATED_FLINK_MANAGER_SETTING=$(echo $FLINK_MANAGER_SETTING | jq --arg new_jar_id "$NEW_JARID" '.flink_config.jar_id = $new_jar_id')
    - aws secretsmanager put-secret-value --secret-id $SECRET_NAME --secret-string "$UPDATED_FLINK_MANAGER_SETTING"
