stages:
  - package and update jar

package and update jar:
  tags:
    - docker
  when: manual
  stage: package and update jar
  image: openjdk:11-jdk
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1
  before_script:
    - apt-get update && apt-get -y upgrade && apt-get install -y curl unzip jq
    - |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
      unzip awscliv2.zip && \
      ./aws/install
  script:
    - mvn clean package
    # - jarid=$(curl -X POST -H "Expect:" -F "jarfile=@./target/mysqlcdc-elasticsearch-1.0-SNAPSHOT.jar" $FLINK_CLUSTER/jars/upload  | jq -r '.filename' | awk -F/ '{print $NF}')
    # - echo $jarid
    # - aws secretsmanager put-secret-value --secret-id flink-manager-setting --secret-string $FLINK_MANAGER_SETTING